image: ruby:2.6.3


# Cache gems in between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby

before_script:
  - gem install bundler:2.0.2
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

stages:
- test
- release

variables:
  DOCKER_TLS_CERTDIR: ""

unit-test:
  tags:
  - dcos-multi-runner
  stage: test
  script:
  - bundle exec rake test
  except:
  - tags

.release: &release
  tags:
  - dcos-multi-runner
  stage: release
  script:
  - gem install gem-release
  - GEM_HOST_API_KEY=$GEM_HOST_API_KEY gem bump fluent-plugin-masking --version $TYPE --commit --push --tag --release 
  when: manual
  only:
  - master

release:patch:
  extends: .release
  variables:
    TYPE: patch

release:minor:
  extends: .release
  variables:
    TYPE: minor

release:major:
  extends: .release
  variables:
    TYPE: major